version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres.1
      POSTGRES_DB: assisdesk_db
    ports:
      - "5432:5432"
